#* You'll need to download a map of Mexico from the [ICESI](http://www.icesi.org.mx/estadisticas/estadisticas_encuestasTablas.asp)
#* You'll also need to download two maps of Mexico at the state and county level from the [INEGI](http://mapserver.inegi.org.mx/data/mgm/). #You'll need to register to do download them
#They have to be version 3.1.1 or they won't work
# Áreas Geoestadísticas Estatales y Zonas Pendientes por Asignar (6.47 Mb)
# Áreas Geoestadísticas Municipales y Zonas Pendientes por Asignar (30.6 Mb)
maps:
    #Change to the location of the INEGI maps
    map.inegi.ct: "maps/MUNICIPIOS.shp"
    map.inegi.st: "maps/ESTADOS.shp"

#Can be Total or Female
sex: Total

states:
    year: 2008 #change to the year you want in the barplot
    year1: 2006 #The first year for the difference barplot
    year2: 2008 #the second year
    mtitle.sm: Mexican homicide rates by state, compared to the national average and grouped by similarity
    ftitle.sm: Mexican femicide rates by state, compared to the national average and grouped by similarity
    mtitle.barplot: Homicide Rates in Mexico -
    ftitle.barplot: Femicide Rates in Mexico -
    mtitle.bardiff: Change in Mexican Homicide Rates (
    ftitle.bardiff: Change in Mexican Femicide Rates (

choropleths:
    mtitle.ch: Homicide rate by municipality
    ftitles.chf: Femicide rate by municipality
